const Router = require('express')
const router = new Router()
const authMiddleware = require('../middleware/auth.middleware')
const fileController = require('../controllers/fileController')

router.post('', authMiddleware, fileController.createDir)
router.post('/upload', authMiddleware, fileController.uploadFile)
router.post('/avatar', authMiddleware, fileController.uploadAvatar)
router.post('/profile', authMiddleware, fileController.setUserProfile)
router.post('/emprofile', authMiddleware, fileController.setEmployeeProfile)
router.post('/addnews', authMiddleware, fileController.addingNews)
router.post('/alluserstatus', authMiddleware, fileController.setStatus)
router.post('/services', authMiddleware, fileController.addingServices)
router.get('/allusers', authMiddleware, fileController.getUsers)
router.get('/allnews', authMiddleware, fileController.getNews)
router.get('/services', authMiddleware, fileController.getServices)
router.get('', authMiddleware, fileController.getFiles)
router.get('/download', authMiddleware, fileController.downloadFile)
router.get('/topemployee', authMiddleware, fileController.getTopEmployee)
router.delete('/', authMiddleware, fileController.deleteFile)
router.delete('/avatar', authMiddleware, fileController.deleteAvatar)
router.delete('/allnews', authMiddleware, fileController.deleteNews)
router.delete('/services', authMiddleware, fileController.deleteServices)
router.delete('/allusers', authMiddleware, fileController.deleteUsers)
module.exports = router